from django.urls import path
from . import views

urlpatterns = [
    path('show_container/', views.show_container, name='show_container'),
    path('show_images/', views.show_images, name='show_images'),
    path('add_new_container/', views.add_new_container, name='add_new_container'),
    path('add_new_image/', views.add_new_image, name='add_new_image'),
    # path('stop_container/', views.stop_container, name='stop_container'),
    path('search_container/', views.search_container, name='search_container'),
    path('delete_container/', views.delete_container, name='delete_container'),
    path('delete_image/', views.delete_image, name='delete_image'),
    # path('start_container/', views.start_container, name='start_container'),
    path('create_course/', views.create_course, name='create_course'),
    path('list_course/', views.list_course, name='list_course'),
    # path('list_course_by_chapter/', views.list_course_by_chapter, name='list_course_by_chapter'),
    path('delete_course/', views.delete_course, name='delete_course'),
    path('get_course_info/', views.get_course_info, name='get_course_info'),
    path('create_experiment/', views.create_experiment, name='create_experiment'),
    path('delete_experiment/', views.delete_experiment, name='delete_experiment'),
    path('delete_experiment_by_course_user/', views.delete_experiment_by_course_user, name='delete_experiment_by_course_user'),
    path('save_experiment/', views.save_experiment, name='save_experiment'),
    path('upload_file/', views.upload_file, name='upload_file'),
    path('upload_tar_file/', views.upload_tar_file, name='upload_tar_file'),
    path('upload_exp_file/', views.upload_exp_file, name='upload_exp_file'),
    path('load_files/', views.load_files, name='load_files'),
    path('download_file/', views.download_file, name='download_files'),
    path('load_experiment_files/', views.load_experiment_files, name='load_experiment_file'),
    path('list_users_have_uploaded/', views.list_users_have_uploaded, name='list_users_have_uploaded'),
    path('list_user_files_uploaded/', views.list_user_files_uploaded, name='list_user_files_uploaded'),
    path('delete_file/', views.delete_file, name='delete_file'),
    path('delete_exp_file/', views.delete_exp_file, name='delete_exp_file'),
    path('list_chapter/', views.list_chapter, name='list_chapter'),
    path('delete_chapter/', views.delete_chapter, name='delete_chapter'),
    path('add_chapter/', views.add_chapter, name='add_chapter'),
    path('rate_experiment/', views.rate_experiment, name='rate_experiment'),
    path('list_user/', views.list_user, name='list_user'),
    path('add_user/', views.add_user, name='add_user'),
    path('delete_user/', views.delete_user, name='delete_user'),
    path('alter_user/', views.alter_user, name='alter_user'),
]
