# Generated by Django 5.0.3 on 2024-06-21 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_rename_exam_type_exam_frame_text_content_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='frame_text_content_id',
        ),
        migrations.AddField(
            model_name='exam',
            name='text_content',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam.textcontent'),
            preserve_default=False,
        ),
    ]
