# Generated by Django 5.0.3 on 2024-06-23 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_remove_exam_frame_text_content_id_exam_text_content'),
        ('users', '0005_userinfo_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='user',
        ),
        migrations.CreateModel(
            name='ExamPaperAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paper_name', models.CharField(max_length=255, verbose_name='试卷名称')),
                ('paper_type', models.IntegerField(verbose_name='试卷类型 (1. 固定试卷, 4. 时段试卷, 6. 任务试卷)')),
                ('system_score', models.IntegerField(verbose_name='系统判定得分')),
                ('user_score', models.IntegerField(verbose_name='最终得分 (千分制)')),
                ('paper_score', models.IntegerField(verbose_name='试卷总分')),
                ('question_correct', models.IntegerField(verbose_name='做对题目数量')),
                ('question_count', models.IntegerField(verbose_name='题目总数量')),
                ('do_time', models.IntegerField(verbose_name='做题时间 (秒)')),
                ('status', models.IntegerField(verbose_name='试卷状态 (1. 待判分, 2. 完成)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userinfo', verbose_name='学生')),
                ('exam_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam', verbose_name='试卷')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.subject', verbose_name='学科')),
            ],
            options={
                'verbose_name': '试卷答案',
                'verbose_name_plural': '试卷答案',
                'db_table': 't_exam_paper_answer',
            },
        ),
        migrations.CreateModel(
            name='ExamPaperQuestionCustomerAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_type', models.IntegerField(verbose_name='题型')),
                ('customer_score', models.IntegerField(verbose_name='得分')),
                ('question_score', models.IntegerField(verbose_name='题目原始分数')),
                ('answer', models.CharField(max_length=255, verbose_name='做题答案')),
                ('do_right', models.BooleanField(verbose_name='是否正确')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('item_order', models.IntegerField(verbose_name='题目顺序')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userinfo', verbose_name='做题人')),
                ('exam_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam', verbose_name='试卷')),
                ('exam_paper_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exampaperanswer', verbose_name='试卷答案')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question', verbose_name='题目')),
                ('question_text_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_text_content', to='exam.textcontent', verbose_name='问题内容')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.subject', verbose_name='学科')),
                ('text_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_text_content', to='exam.textcontent', verbose_name='做题内容')),
            ],
            options={
                'verbose_name': '试卷题目答案',
                'verbose_name_plural': '试卷题目答案',
                'db_table': 't_exam_paper_question_customer_answer',
            },
        ),
        migrations.DeleteModel(
            name='ExamQuestion',
        ),
        migrations.DeleteModel(
            name='Paper',
        ),
    ]
