# Generated by Django 5.0.3 on 2024-03-12 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Container",
            fields=[
                (
                    "container_id",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="容器ID",
                    ),
                ),
                (
                    "container_name",
                    models.CharField(max_length=100, verbose_name="容器名词"),
                ),
                ("container_url", models.URLField(verbose_name="容器URL")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="容器创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="容器更新时间"),
                ),
                (
                    "author_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.userinfo"
                    ),
                ),
            ],
            options={
                "verbose_name": "容器信息",
                "verbose_name_plural": "容器信息",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "course_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="课程ID"
                    ),
                ),
                ("course_name", models.CharField(max_length=100, verbose_name="课程名城")),
                (
                    "course_intro",
                    models.CharField(max_length=1000, verbose_name="课程简介"),
                ),
                ("course_chapter", models.IntegerField(verbose_name="课程章节")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="课程创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="课程更新时间"),
                ),
                (
                    "use_container_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teacher.container",
                    ),
                ),
            ],
            options={
                "verbose_name": "容器信息",
                "verbose_name_plural": "容器信息",
            },
        ),
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "image_id",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="镜像ID",
                    ),
                ),
                ("image_name", models.CharField(max_length=100, verbose_name="镜像名")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="镜像创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="镜像更新时间"),
                ),
                (
                    "author_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.userinfo"
                    ),
                ),
            ],
            options={
                "verbose_name": "镜像信息",
                "verbose_name_plural": "镜像信息",
            },
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(default=0, verbose_name="实验分数")),
                (
                    "course_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="teacher.course"
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.userinfo"
                    ),
                ),
            ],
        ),
    ]
