# Generated by Django 5.0.3 on 2024-03-20 03:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teacher", "0002_alter_score_options_alter_container_container_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="container",
            name="author_id",
        ),
        migrations.RemoveField(
            model_name="images",
            name="author_id",
        ),
    ]
