# Generated by Django 5.0.3 on 2024-03-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teacher", "0003_remove_container_author_id_remove_images_author_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="container_status",
            field=models.CharField(default=1, max_length=100, verbose_name="容器运行状态"),
            preserve_default=False,
        ),
    ]
