# Generated by Django 5.0.3 on 2024-03-25 11:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teacher", "0004_container_container_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="container",
            name="container_status",
        ),
    ]
