# Generated by Django 5.0.3 on 2024-03-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teacher", "0005_remove_container_container_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_difficulty",
            field=models.CharField(default="简单", max_length=100, verbose_name="课程难度"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="course_limit_time",
            field=models.IntegerField(default=0, verbose_name="课程限时"),
        ),
    ]
