# Generated by Django 5.0.3 on 2024-03-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teacher", "0006_course_course_difficulty_course_course_limit_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="use_container_id",
        ),
        migrations.AddField(
            model_name="course",
            name="course_aim",
            field=models.CharField(default=" ", max_length=1000, verbose_name="课程目标"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="use_image_name",
            field=models.CharField(default="目标", max_length=100, verbose_name="使用镜像名"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course",
            name="course_name",
            field=models.CharField(max_length=100, verbose_name="课程名称"),
        ),
    ]
