# Generated by Django 5.0.3 on 2024-04-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teacher", "0010_experiment_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="cpu_num",
            field=models.FloatField(default="1", verbose_name="CPU数量"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="container",
            name="http_port",
            field=models.IntegerField(default=1, verbose_name="http端口"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="container",
            name="mem_size",
            field=models.FloatField(default=1, verbose_name="内存大小"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="container",
            name="ssh_port",
            field=models.IntegerField(default=1, verbose_name="ssh端口"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="images",
            name="cpu_num",
            field=models.FloatField(default=1, verbose_name="CPU数量"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="images",
            name="http_port",
            field=models.IntegerField(default="1", verbose_name="http端口"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="images",
            name="mem_size",
            field=models.FloatField(default="1", verbose_name="内存大小"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="images",
            name="ssh_port",
            field=models.IntegerField(default="1", verbose_name="ssh端口"),
            preserve_default=False,
        ),
    ]
