# Generated by Django 5.0.3 on 2024-04-12 06:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teacher", "0011_container_cpu_num_container_http_port_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="container",
            name="http_port",
        ),
        migrations.RemoveField(
            model_name="container",
            name="ssh_port",
        ),
        migrations.RemoveField(
            model_name="images",
            name="http_port",
        ),
        migrations.RemoveField(
            model_name="images",
            name="ssh_port",
        ),
    ]
