# Generated by Django 5.0.3 on 2024-04-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "teacher",
            "0012_remove_container_http_port_remove_container_ssh_port_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="cpu_num",
            field=models.CharField(max_length=100, verbose_name="CPU数量"),
        ),
        migrations.AlterField(
            model_name="container",
            name="mem_size",
            field=models.CharField(max_length=100, verbose_name="内存大小"),
        ),
        migrations.AlterField(
            model_name="images",
            name="cpu_num",
            field=models.CharField(max_length=100, verbose_name="CPU数量"),
        ),
        migrations.AlterField(
            model_name="images",
            name="mem_size",
            field=models.CharField(max_length=100, verbose_name="内存大小"),
        ),
    ]
