# Generated by Django 5.0.3 on 2024-04-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teacher", "0013_alter_container_cpu_num_alter_container_mem_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="http_port",
            field=models.IntegerField(default=1, verbose_name="HTTP端口"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="container",
            name="ssh_port",
            field=models.IntegerField(default="1", verbose_name="SSH端口"),
            preserve_default=False,
        ),
    ]
