# Generated by Django 5.0.3 on 2024-04-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teacher", "0014_container_http_port_container_ssh_port"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="ssh_password",
            field=models.CharField(default="1", max_length=100, verbose_name="SSH密码"),
            preserve_default=False,
        ),
    ]
