# Generated by Django 5.0.3 on 2024-04-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teacher", "0015_container_ssh_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="base_image",
            field=models.CharField(default="1", max_length=100, verbose_name="基于镜像"),
            preserve_default=False,
        ),
    ]
