# Generated by Django 5.0.3 on 2024-04-17 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teacher", "0016_container_base_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "chapter_number",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="章节编号"
                    ),
                ),
                ("chapter_name", models.CharField(max_length=100, verbose_name="章节名词")),
            ],
        ),
        migrations.AlterField(
            model_name="course",
            name="course_chapter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="teacher.chapter"
            ),
        ),
    ]
