# Generated by Django 5.0.3 on 2024-04-17 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teacher", "0017_chapter_alter_course_course_chapter"),
        ("users", "0002_alter_userinfo_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="author_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="users.userinfo"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_chapter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="teacher.chapter"
            ),
        ),
    ]
