# Generated by Django 5.0.3 on 2024-03-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100, verbose_name="用户名")),
                ("password", models.CharField(max_length=100, verbose_name="密码")),
                ("realname", models.CharField(max_length=100, verbose_name="真实姓名")),
                ("email", models.EmailField(max_length=254, verbose_name="邮箱")),
                ("phone", models.CharField(max_length=100, verbose_name="电话号码")),
                (
                    "status",
                    models.CharField(
                        choices=[(1, "学生"), (2, "教师"), (3, "管理员")],
                        max_length=100,
                        verbose_name="用户身份",
                    ),
                ),
            ],
            options={
                "verbose_name": "镜像信息",
                "verbose_name_plural": "镜像信息",
            },
        ),
    ]
