# Generated by Django 5.0.1 on 2024-04-10 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="status",
            field=models.CharField(max_length=100, verbose_name="用户身份"),
        ),
    ]
