# Generated by Django 5.0.3 on 2024-06-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userinfo_email_alter_userinfo_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='birth_day',
            field=models.DateTimeField(blank=True, null=True, verbose_name='出生日期'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default='2023-01-01 00:00:00', verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='role',
            field=models.IntegerField(blank=True, null=True, verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='sex',
            field=models.IntegerField(blank=True, null=True, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_level',
            field=models.IntegerField(blank=True, null=True, verbose_name='用户等级'),
        ),
    ]
