# Generated by Django 5.0.3 on 2024-06-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userinfo_age_userinfo_birth_day_userinfo_create_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
