# Generated by Django 5.0.3 on 2024-06-23 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userinfo_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('current_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userinfo')),
            ],
        ),
    ]
